package pojos;
// Generated 2019.12.17. 15:34:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name="customers"
    ,catalog="webshop_pc"
)
public class Customers  implements java.io.Serializable {


     private Integer customerId;
     private String name;
     private String email;
     private String pass;
     private String phone;
     private String city;
     private String address;
     private Set<Orders> orderses = new HashSet<Orders>(0);

    public Customers() {
    }
    public Customers(String name, String email, String pass, String phone, String city, String address) {
       this.name = name;
       this.email = email;
       this.pass = pass;
       this.phone = phone;
       this.city = city;
       this.address = address;
       this.orderses = orderses;
    }
    public Customers(String name, String email, String pass, String phone, String city, String address, Set<Orders> orderses) {
       this.name = name;
       this.email = email;
       this.pass = pass;
       this.phone = phone;
       this.city = city;
       this.address = address;
       this.orderses = orderses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="customer_id", unique=true, nullable=false)
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="pass", length=45)
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }

    
    @Column(name="phone", length=45)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="address", length=45)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="customers")
    public Set<Orders> getOrderses() {
        return this.orderses;
    }
    
    public void setOrderses(Set<Orders> orderses) {
        this.orderses = orderses;
    }




}


