package pojos;
// Generated 2019.12.17. 15:34:04 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Orderdetials generated by hbm2java
 */
@Entity
@Table(name="orderdetials"
    ,catalog="webshop_pc"
)
public class Orderdetials  implements java.io.Serializable {


     private Integer id;
     private Orders orders;
     private Products products;
     private Integer orderQty;

    public Orderdetials() {
    }

	
    public Orderdetials(Orders orders, Products products) {
        this.orders = orders;
        this.products = products;
    }
    public Orderdetials(Orders orders, Products products, Integer orderQty) {
       this.orders = orders;
       this.products = products;
       this.orderQty = orderQty;
    }

    @Override
    public String toString() {
        return  orderQty + " X " +  products.getProductName() + "\n" + products.getManufacturer() + "\n" + products.getDescription() + "\n";
    }
       
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="orderNumber_id", nullable=false)
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="productCode", nullable=false)
    public Products getProducts() {
        return this.products;
    }
    
    public void setProducts(Products products) {
        this.products = products;
    }

    
    @Column(name="orderQty", nullable=false)
    public Integer getOrderQty() {
        return this.orderQty;
    }
    
    public void setOrderQty(Integer orderQty) {
        this.orderQty = orderQty;
    }




}


