package pojos;
// Generated 2019.12.17. 15:34:04 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name="orders"
    ,catalog="webshop_pc"
)
public class Orders  implements java.io.Serializable {


     private int orderNumberId;
     private Customers customers;
     private Date orderDate;
     private boolean status;
     private String comment;
     private Set<Orderdetials> orderdetialses = new HashSet<Orderdetials>(0);

    public Orders() {
    }

	
    public Orders(int orderNumberId, Customers customers, boolean status) {
        this.orderNumberId = orderNumberId;
        this.customers = customers;
        this.status = status;
    }
    public Orders(Customers customers, Date orderDate, boolean status, String comment) {
       this.customers = customers;
       this.orderDate = orderDate;
       this.status = status;
       this.comment = comment;
    }
    public Orders(int orderNumberId, Customers customers, Date orderDate, boolean status, String comment, Set<Orderdetials> orderdetialses) {
       this.orderNumberId = orderNumberId;
       this.customers = customers;
       this.orderDate = orderDate;
       this.status = status;
       this.comment = comment;
       this.orderdetialses = orderdetialses;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="orderNumber_id", unique=true, nullable=false)
    public int getOrderNumberId() {
        return this.orderNumberId;
    }
    
    public void setOrderNumberId(int orderNumberId) {
        this.orderNumberId = orderNumberId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="customer_id", nullable=false)
    public Customers getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Customers customers) {
        this.customers = customers;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="orderDate", length=19)
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    
    @Column(name="status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="comment", length=45)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="orders")
    public Set<Orderdetials> getOrderdetialses() {
        return this.orderdetialses;
    }
    
    public void setOrderdetialses(Set<Orderdetials> orderdetialses) {
        this.orderdetialses = orderdetialses;
    }




}


