package pojos;
// Generated 2019.12.17. 15:34:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="webshop_pc"
)
public class Products  implements java.io.Serializable {


     private Integer productCodeId;
     private Productlines productlines;
     private String productName;
     private String manufacturer;
     private String description;
     private String warranty;
     private Integer price;
     private Set<Orderdetials> orderdetialses = new HashSet<Orderdetials>(0);

    public Products() {
    }

	
    public Products(Productlines productlines) {
        this.productlines = productlines;
    }
    public Products(Productlines productlines, String productName, String manufacturer, String description, String warranty, Integer price, Set<Orderdetials> orderdetialses) {
       this.productlines = productlines;
       this.productName = productName;
       this.manufacturer = manufacturer;
       this.description = description;
       this.warranty = warranty;
       this.price = price;
       this.orderdetialses = orderdetialses;
    }

    @Override
    public String toString() {
        return productName + ", " + manufacturer + ", " + description + ", " + warranty;
    }
   
    
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="productCode_id", unique=true, nullable=false)
    public Integer getProductCodeId() {
        return this.productCodeId;
    }
    
    public void setProductCodeId(Integer productCodeId) {
        this.productCodeId = productCodeId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="productLine", nullable=false)
    public Productlines getProductlines() {
        return this.productlines;
    }
    
    public void setProductlines(Productlines productlines) {
        this.productlines = productlines;
    }

    
    @Column(name="productName", length=45)
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="manufacturer", length=45)
    public String getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer;
    }

    
    @Column(name="description", length=90)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="warranty", length=45)
    public String getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(String warranty) {
        this.warranty = warranty;
    }

    
    @Column(name="price")
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="products")
    public Set<Orderdetials> getOrderdetialses() {
        return this.orderdetialses;
    }
    
    public void setOrderdetialses(Set<Orderdetials> orderdetialses) {
        this.orderdetialses = orderdetialses;
    }




}


