package pojos;
// Generated 2019.12.17. 15:34:04 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productlines generated by hbm2java
 */
@Entity
@Table(name="productlines"
    ,catalog="webshop_pc"
)
public class Productlines  implements java.io.Serializable {


     private String productlinesId;
     private String description;
     private Set<Products> productses = new HashSet<Products>(0);

    public Productlines() {
    }

	
    public Productlines(String productlinesId) {
        this.productlinesId = productlinesId;
    }
    public Productlines(String productlinesId, String description, Set<Products> productses) {
       this.productlinesId = productlinesId;
       this.description = description;
       this.productses = productses;
    }

    @Override
    public String toString() {
        return productlinesId;
    }
  
    @Id 

    
    @Column(name="productlines_id", unique=true, nullable=false, length=45)
    public String getProductlinesId() {
        return this.productlinesId;
    }
    
    public void setProductlinesId(String productlinesId) {
        this.productlinesId = productlinesId;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="productlines")
    public Set<Products> getProductses() {
        return this.productses;
    }
    
    public void setProductses(Set<Products> productses) {
        this.productses = productses;
    }




}


